using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Okapi.DataSourceHandlers.EnumHandlers;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData() => new List<DataSourceItem>
    {
        new("ab", "Abkhazian"),
        new("ab", "Abkhazian"),
        new("ab-GE", "Abkhazian (*Georgia)"),
        new("om", "Afaan Oromo"),
        new("om-ET", "Afaan Oromo (*Ethiopia)"),
        new("aa", "Afar"),
        new("aa-DJ", "Afar (*Djibouti)"),
        new("af", "Afrikaan"),
        new("af-ZA", "Afrikaan (*South Africa)"),
        new("am", "Amharic"),
        new("am-ET", "Amharic (*Etiopia)"),
        new("ar", "Arabic"),
        new("ar-SA", "Arabic (*Saudi Arabia)"),
        new("ar-DZ", "Arabic (Algeria)"),
        new("ar-BH", "Arabic (Bahrain)"),
        new("ar-KM", "Arabic (Comoros)"),
        new("ar-DJ", "Arabic (Djibouti)"),
        new("ar-EG", "Arabic (Egypt)"),
        new("ar-IQ", "Arabic (Iraq)"),
        new("ar-JO", "Arabic (Jordan)"),
        new("ar-KW", "Arabic (Kuwait)"),
        new("ar-LB", "Arabic (Lebanon)"),
        new("ar-LY", "Arabic (Libya)"),
        new("ar-MA", "Arabic (Morocco)"),
        new("ar-OM", "Arabic (Oman)"),
        new("ar-PS", "Arabic (Palestine)"),
        new("ar-QA", "Arabic (Qatar)"),
        new("ar-SD", "Arabic (Sudan)"),
        new("ar-SY", "Arabic (Syria)"),
        new("ar-TN", "Arabic (Tunisia)"),
        new("ar-AE", "Arabic (U.A.E.)"),
        new("ar-YE", "Arabic (Yemen)"),
        new("hy", "Armenian"),
        new("hy-AM", "Armenian (*Armenia)"),
        new("as", "Assamese"),
        new("as-IN", "Assamese (*India)"),
        new("ay", "Aymara"),
        new("ay-BO", "Aymara (*Bolivia)"),
        new("az", "Azerbaijani"),
        new("az-AZ", "Azerbaijani (*Azerbaijan)"),
        new("az-Cyrl-AZ", "Azerbaijani (Azerbaijan, Cyrillic)"),
        new("ba", "Bashkir"),
        new("ba-RU", "Bashkir (*Russia)"),
        new("eu", "Basque"),
        new("eu-ES", "Basque (*Spain)"),
        new("be", "Belarusian"),
        new("be-BY", "Belarusian (*Belarus)"),
        new("bn", "Bengali"),
        new("bn-BD", "Bengali (*Bengladesh)"),
        new("dz", "Bhutani"),
        new("dz-BT", "Bhutani (*Bhutan)"),
        new("bh", "Bihari"),
        new("bh-IN", "Bihari (*India)"),
        new("bi", "Bislama"),
        new("bi-VU", "Bislama (*Vanuatu)"),
        new("bs", "Bosnian"),
        new("bs-BA", "Bosnian (*Bosnia and Herzegovina)"),
        new("br", "Breton"),
        new("br-FR", "Breton (*France)"),
        new("bg", "Bulgarian"),
        new("bg-BG", "Bulgarian (*Bulgaria)"),
        new("my", "Burmese"),
        new("my-MM", "Burmese (*Myanmar)"),
        new("ca", "Catalan"),
        new("ca-ES", "Catalan (*Spain)"),
        new("zh", "Chinese"),
        new("zh-CN", "Chinese (*China, =Simplified)"),
        new("zh-HK", "Chinese (Hong-Kong)"),
        new("zh-MO", "Chinese (Macau)"),
        new("zh-SG", "Chinese (Singapore)"),
        new("zh-TW", "Chinese (Taiwan, =Traditional)"),
        new("zh-Hans", "Chinese (Simplified)"),
        new("zh-Hant", "Chinese (Traditional)"),
        new("kw", "Cornish Gaelic"),
        new("kw-GB", "Cornish Gaelic (*United Kingdom)"),
        new("co", "Corsican"),
        new("co-FR", "Corsican (*France)"),
        new("ht", "Haitian Creole"),
        new("ht-HT", "Haitian Creole (*Haiti)"),
        new("hr", "Croatian"),
        new("hr-HR", "Croatian (*Croatia)"),
        new("hr-BA", "Croatian (Bosnia and Herzegovina)"),
        new("cs", "Czech"),
        new("cs-CZ", "Czech (*Czech Republic)"),
        new("da", "Danish"),
        new("da-DK", "Danish (Denmark)"),
        new("snm", "Dhivehi"),
        new("snm-MV", "Dhivehi (*Maldives)"),
        new("nl", "Dutch"),
        new("nl-NL", "Dutch (*The Netherlands)"),
        new("nl-BE", "Dutch (Belgium, =Flemish)"),
        new("nl-SR", "Dutch (Surinam)"),
        new("en", "English"),
        new("en-US", "English (*United States)"),
        new("en-AU", "English (Australia)"),
        new("en-BS", "English (Bahamas)"),
        new("en-BB", "English (Barbados)"),
        new("en-BZ", "English (Belize)"),
        new("en-CA", "English (Canada)"),
        new("en-DM", "English (Dominica)"),
        new("en-GM", "English (Gambia)"),
        new("en-GH", "English (Ghana)"),
        new("en-GD", "English (Grenada)"),
        new("en-GY", "English (Guyana)"),
        new("en-IE", "English (Ireland)"),
        new("en-IN", "English (India)"),
        new("en-JM", "English (Jamaica)"),
        new("en-KI", "English (Kiribati)"),
        new("en-LS", "English (Lesotho)"),
        new("en-LR", "English (Liberia)"),
        new("en-MW", "English (Malawi)"),
        new("en-MU", "English (Mauritius)"),
        new("en-NA", "English (Namibia)"),
        new("en-NZ", "English (New Zealand)"),
        new("en-NG", "English (Nigeria)"),
        new("en-PG", "English (Papua New-Guinea)"),
        new("en-PH", "English (Philippines)"),
        new("en-ZA", "English (South Africa)"),
        new("en-SL", "English (Sierra Leone)"),
        new("en-VC", "English (St Vincent and the Grenadines)"),
        new("en-TT", "English (Trinidad and Tobago)"),
        new("en-GB", "English (United Kingdom)"),
        new("x-en-Carib", "English (Windows Caribbean)"),
        new("x-en-Neutral", "English (Windows Neutral)"),
        new("en-ZM", "English (Zambia)"),
        new("en-ZW", "English (Zimbabwe)"),
        new("eo", "Esperanto"),
        new("et", "Estonian"),
        new("et-EE", "Estonian (*Estonia)"),
        new("fo", "Faeroese"),
        new("fo-FO", "Faeroese (*Faeroese Islands)"),
        new("fa", "Farsi"),
        new("fa-IR", "Farsi (*Iran)"),
        new("fj", "Fijian"),
        new("fj-FJ", "Fijian (*Fiji)"),
        new("fi", "Finnish"),
        new("fi-FI", "Finnish (*Finland)"),
        new("fr", "French"),
        new("fr-FR", "French (*France)"),
        new("fr-BE", "French (Belgium)"),
        new("fr-BF", "French (Burkina Faso)"),
        new("fr-CM", "French (Cameroon)"),
        new("fr-CA", "French (Canada, =Québécois)"),
        new("fr-TD", "French (Chad)"),
        new("fr-KM", "French (Comoros)"),
        new("fr-CG", "French (Congo)"),
        new("fr-CI", "French (Côte d'Ivoire)"),
        new("fr-DJ", "French (Djibouti)"),
        new("fr-GA", "French (Gabon)"),
        new("fr-GN", "French (Guinea)"),
        new("fr-HT", "French (Haiti)"),
        new("fr-LU", "French (Luxembourg)"),
        new("fr-ML", "French (Mali)"),
        new("fr-MR", "French (Mauritania)"),
        new("fr-MC", "French (Monaco)"),
        new("fr-SN", "French (Senegal)"),
        new("fr-CH", "French (Switzerland)"),
        new("fr-TG", "French (Togo)"),
        new("fr-ZR", "French (Zaire)"),
        new("fy", "Frisian"),
        new("fy-NL", "Frisian (*The Netherlands)"),
        new("gl", "Galician"),
        new("gl-ES", "Gallegan (*Spain)"),
        new("ka", "Georgian"),
        new("ka-GE", "Georian (*Georgia)"),
        new("de", "German"),
        new("de-DE", "German (*Germany)"),
        new("de-AT", "German (Austria)"),
        new("de-LI", "German (Liechtenstein)"),
        new("de-LU", "German (Luxembourg)"),
        new("de-CH", "German (Switzerland)"),
        new("gil", "Gilbertese"),
        new("gil-KI", "Gilbertese (*Kiribati)"),
        new("gil-TV", "Gilbertese (Tuvalu)"),
        new("el", "Greek"),
        new("el-GR", "Greek (*Greece)"),
        new("el-CY", "Greek (Cyprus)"),
        new("gn", "Guarani"),
        new("gn-PY", "Guarani (*Paraguay)"),
        new("gu", "Gujarati"),
        new("gu-IN", "Gujarati (*India)"),
        new("ha", "Hausa"),
        new("ha-NG", "Hausa (*Nigeria)"),
        new("he", "Hebrew"),
        new("he-IL", "Hebrew (*Israel)"),
        new("hi", "Hindi"),
        new("hi-IN", "Hindi (*India)"),
        new("hu", "Hungarian"),
        new("hu-HU", "Hungarian (*Hungarian)"),
        new("is", "Icelandic"),
        new("is-IS", "Icelandic (*Iceland)"),
        new("id", "Indonesian"),
        new("id-id", "Indonesian (*Indonesia)"),
        new("ia", "Interlingua"),
        new("ie", "Interlingue"),
        new("iu", "Inuktitut"),
        new("iu-CA", "Inuktitut (*Canada)"),
        new("ik", "Inupiak"),
        new("ik-US", "Inupiak (*United States)"),
        new("ga", "Irish Gaelic"),
        new("ga-IE", "Irish Gaelic (*Ireland)"),
        new("it", "Italian"),
        new("it-IT", "Italian (*Italy)"),
        new("it-SM", "Italian (San Marino)"),
        new("it-CH", "Italian (Switzerland)"),
        new("ja", "Japanese"),
        new("ja-JP", "Japanese (*Japan)"),
        new("jw", "Javanese"),
        new("jw-ID", "Javanese (*Indonesia)"),
        new("kl", "Kalaallisut"),
        new("kl-GL", "Kalaallisut (*Greenland)"),
        new("kn", "Kannada"),
        new("kn-IN", "Kannada (*India)"),
        new("ks", "Kashmiri"),
        new("ks-IN", "Kashmiri (*India)"),
        new("kk", "Kazakh"),
        new("kk-KZ", "Kazakh (*Kazakhstan)"),
        new("rw", "Kinyarwanda"),
        new("rw-RW", "Kinyarwanda (*Rwanda)"),
        new("ky", "Kirghiz"),
        new("ky-KG", "Kirghiz (*Kyrgyzstan)"),
        new("rn", "Kirundi"),
        new("rn-BI", "Kirundi (*Burundi)"),
        new("km", "Khmer"),
        new("km-KH", "Khmer (*Cambodia)"),
        new("kok", "Konkani"),
        new("kok-IN", "Konkani (*India)"),
        new("ko", "Korean"),
        new("ko-KR", "Korean (*Korea)"),
        new("ko-KP", "Korean (North Korea)"),
        new("lo", "Lao"),
        new("lo-LA", "Lao (*Laos)"),
        new("lap", "Lappish"),
        new("lap-NO", "Lappish (*Norway)"),
        new("la", "Latin"),
        new("la-VA", "Latin (*Vatican)"),
        new("lv", "Latvian"),
        new("lv-LV", "Latvian (*Latvia)"),
        new("ln", "Lingala"),
        new("ln-CG", "Lingala (*Congo)"),
        new("lt", "Lithuanian"),
        new("lt-LT", "Lithuanian (*Lithuania)"),
        new("x-lt-LT-Classic", "Lithuanian (Lithuania, Classical)"),
        new("lb", "Luxemburgian"),
        new("lb-LU", "Luxemburgian (*Luxembourg)"),
        new("mk", "Macedonian"),
        new("mk-MK", "Macedonian (*Macedonia)"),
        new("mg", "Malagasy"),
        new("mg-MG", "Malagasy (*Madagascar)"),
        new("ms", "Malay"),
        new("ms-MY", "Malay (*Malaysia)"),
        new("ms-BN", "Malay (Brunei Darussalam)"),
        new("ml", "Malayalam"),
        new("ml-IN", "Malayalam (*India)"),
        new("mt", "Maltese"),
        new("mt-MT", "Maltese (*Malta)"),
        new("mni", "Manipuri"),
        new("mni-IN", "Manipuri (*India)"),
        new("gv", "Manx Gaelic"),
        new("gv-GB", "Manx Gaelic (*United Kingdom)"),
        new("mi", "Maori"),
        new("mi-NZ", "Maori (*New Zealand)"),
        new("mr", "Marathi"),
        new("mr-IN", "Marathi (*India)"),
        new("mo", "Moldovan"),
        new("mo-MD", "Moldovan (*Moldova)"),
        new("mn", "Mongolian"),
        new("mn-MN", "Mongolian (*Mongolia)"),
        new("na", "Nauruan"),
        new("na-NR", "Nauruan (*Nauru)"),
        new("nv", "Navajo"),
        new("nv-US", "Navajo (*United States)"),
        new("ne", "Nepali"),
        new("ne-NP", "Nepali (*Nepal)"),
        new("ne-IN", "Nepali (India)"),
        new("no", "Norwegian"),
        new("no-NO", "Norwegian (*Norway)"),
        new("nn-NO", "Norwegian Nynorsk (*Norway)"),
        new("oc", "Occitan"),
        new("oc-FR", "Occitan (*France)"),
        new("or", "Oriya"),
        new("or-IN", "Oriya (*India)"),
        new("ps", "Pashto"),
        new("ps-AF", "Pashto (*Afghanistan)"),
        new("pl", "Polish"),
        new("pl-PL", "Polish (*Poland)"),
        new("pt", "Portuguese"),
        new("pt-BR", "Portuguese (*Brazil)"),
        new("pt-AO", "Portuguese (Angola)"),
        new("pt-CV", "Portuguese (Cape Verde)"),
        new("pt-GW", "Portuguese (Guinea-Bissau)"),
        new("pt-MZ", "Portuguese (Mozambique)"),
        new("pt-PT", "Portuguese (Portugal)"),
        new("pa", "Punjabi"),
        new("pa-IN", "Punjabi (*India)"),
        new("qu", "Quechua"),
        new("qu-PE", "Quechua (*Peru)"),
        new("ro", "Romanian"),
        new("ro-ro", "Romanian (*Romania)"),
        new("ro-md", "Romanian (Moldova)"),
        new("rm", "Raetho-Roman"),
        new("rm-ch", "Raetho-Roman (*Switzerland)"),
        new("ru", "Russian"),
        new("ru-ru", "Russian (*Russia)"),
        new("ru-md", "Russian (Moldova)"),
        new("sa", "Sanskrit"),
        new("sa-in", "Sanskrit (*India)"),
        new("sd", "Sindhi"),
        new("sd-in", "Sindhi (*India)"),
        new("si", "Singhalese"),
        new("si-lk", "Singhalese (*Sri-Lanka)"),
        new("sk", "Slovak"),
        new("sk-sk", "Slovak (*Slovakia)"),
        new("sl", "Slovenian"),
        new("sl-si", "Slovenian (*Slovenia)"),
        new("sm", "Samoan"),
        new("sm-ws", "Samoan (*Western Samoa)"),
        new("sq", "Albanian"),
        new("sq-AL", "Albanian (*Albania)"),
        new("sr", "Serbian"),
        new("sr-Cyrl-SP", "Serbian (*Serbia)"),
        new("sr-Cyrl-BA", "Serbian (Bosnia and Herzegovina)"),
        new("ss", "Siswati"),
        new("ss-sz", "Siswati (*Swaziland)"),
        new("ss-za", "Siswati (South-Africa)"),
        new("st", "Sesotho"),
        new("st-ls", "Sesotho (*Lesotho)"),
        new("sv", "Swedish"),
        new("sv-SE", "Swedish (*Sweden)"),
        new("sv-AX", "Swedish (Åland Islands)"),
        new("sv-FI", "Swedish (Finland)"),
        new("sw", "Swahili"),
        new("sw-KE", "Swahili (*Kenya)"),
        new("syr", "Syriac"),
        new("gd", "Scottish Gaelic"),
        new("gd-GB", "Scottish Gaelic (*United Kingdom)"),
        new("tet", "Tetum"),
        new("tet-TL", "Tetum (*Timor-Leste)"),
        new("yo", "Yoruba"),
        new("yo-NG", "Yoruba (*Nigeria)"),
        new("yi", "Yiddish"),
        new("yi-IL", "Yiddish (*Israel)"),
        new("vi", "Vietnamese"),
        new("vi-VN", "Vietnamese (*Vietnam)"),
        new("wo", "Wolof"),
        new("wo-SN", "Wolof (*Senegal)"),
        new("wen", "Sorbian"),
        new("wen-DE", "Sorbian (*Germany)"),
        new("x-win-Neutral", "Windows Neutral"),
        new("x-win-Default", "Windows Neutral (Default)"),
        new("x-win-System", "Windows Neutral (System)"),
        new("bo", "Tibetan"),
        new("bo-ZH", "Tibetan (*China)"),
        new("cy", "Welsh"),
        new("cy-GB", "Welsh (*United Kingdom)"),
        new("es", "Spanish"),
        new("es-ES", "Spanish (*Spain)"),
        new("es-AR", "Spanish (Argentina)"),
        new("es-BO", "Spanish (Bolivia)"),
        new("es-CL", "Spanish (Chile)"),
        new("es-CO", "Spanish (Colombia)"),
        new("es-CR", "Spanish (Costa Rica)"),
        new("es-CU", "Spanish (Cuba)"),
        new("es-DO", "Spanish (Dominican Republic)"),
        new("es-EC", "Spanish (Ecuador)"),
        new("es-GQ", "Spanish (Equatorial Guinea)"),
        new("es-GT", "Spanish (Guatemala)"),
        new("es-HN", "Spanish (Honduras)"),
        new("es-MX", "Spanish (Mexico)"),
        new("es-NI", "Spanish (Nicaragua)"),
        new("es-PA", "Spanish (Panama)"),
        new("es-PE", "Spanish (Peru)"),
        new("es-PR", "Spanish (Puerto Rico)"),
        new("es-PY", "Spanish (Paraguay)"),
        new("es-SV", "Spanish (El Salvador)"),
        new("es-UY", "Spanish (Uruguay)"),
        new("es-VE", "Spanish (Venezuela)"),
        new("es-419", "Spanish (Latin American &amp; the Caribbean)"),
        new("es-x-Modern", "Spanish (Modern Sort)"),
        new("th", "Thai"),
        new("th-TH", "Thai (*Thailand)"),
        new("tr", "Turkish"),
        new("tr-TR", "Turkish (*Turkey)"),
        new("tr-CY", "Turkish (Cyprus)"),
        new("uk", "Ukrainian"),
        new("uk-UA", "Ukrainian (*Ukraine)"),
        new("ur", "Urdu"),
        new("uk-PK", "Urdu (*Pakistan)"),
        new("ug", "Uighur"),
        new("ug-CN", "Uighur (*China)"),
        new("zu", "Zulu"),
        new("zu-ZA", "Zulu (*south Africa)"),
    };
}