using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Okapi.DataSourceHandlers.EnumHandlers;

public class LanguageDataHandler : IStaticDataSourceItemHandler
{
    public IEnumerable<DataSourceItem> GetData() =>
    [
        new() { Value = "ab", DisplayName = "Abkhazian" },
        new() { Value = "ab", DisplayName = "Abkhazian" },
        new() { Value = "ab-GE", DisplayName = "Abkhazian (*Georgia)" },
        new() { Value = "om", DisplayName = "Afaan Oromo" },
        new() { Value = "om-ET", DisplayName = "Afaan Oromo (*Ethiopia)" },
        new() { Value = "aa", DisplayName = "Afar" },
        new() { Value = "aa-DJ", DisplayName = "Afar (*Djibouti)" },
        new() { Value = "af", DisplayName = "Afrikaan" },
        new() { Value = "af-ZA", DisplayName = "Afrikaan (*South Africa)" },
        new() { Value = "am", DisplayName = "Amharic" },
        new() { Value = "am-ET", DisplayName = "Amharic (*Etiopia)" },
        new() { Value = "ar", DisplayName = "Arabic" },
        new() { Value = "ar-SA", DisplayName = "Arabic (*Saudi Arabia)" },
        new() { Value = "ar-DZ", DisplayName = "Arabic (Algeria)" },
        new() { Value = "ar-BH", DisplayName = "Arabic (Bahrain)" },
        new() { Value = "ar-KM", DisplayName = "Arabic (Comoros)" },
        new() { Value = "ar-DJ", DisplayName = "Arabic (Djibouti)" },
        new() { Value = "ar-EG", DisplayName = "Arabic (Egypt)" },
        new() { Value = "ar-IQ", DisplayName = "Arabic (Iraq)" },
        new() { Value = "ar-JO", DisplayName = "Arabic (Jordan)" },
        new() { Value = "ar-KW", DisplayName = "Arabic (Kuwait)" },
        new() { Value = "ar-LB", DisplayName = "Arabic (Lebanon)" },
        new() { Value = "ar-LY", DisplayName = "Arabic (Libya)" },
        new() { Value = "ar-MA", DisplayName = "Arabic (Morocco)" },
        new() { Value = "ar-OM", DisplayName = "Arabic (Oman)" },
        new() { Value = "ar-PS", DisplayName = "Arabic (Palestine)" },
        new() { Value = "ar-QA", DisplayName = "Arabic (Qatar)" },
        new() { Value = "ar-SD", DisplayName = "Arabic (Sudan)" },
        new() { Value = "ar-SY", DisplayName = "Arabic (Syria)" },
        new() { Value = "ar-TN", DisplayName = "Arabic (Tunisia)" },
        new() { Value = "ar-AE", DisplayName = "Arabic (U.A.E.)" },
        new() { Value = "ar-YE", DisplayName = "Arabic (Yemen)" },
        new() { Value = "hy", DisplayName = "Armenian" },
        new() { Value = "hy-AM", DisplayName = "Armenian (*Armenia)" },
        new() { Value = "as", DisplayName = "Assamese" },
        new() { Value = "as-IN", DisplayName = "Assamese (*India)" },
        new() { Value = "ay", DisplayName = "Aymara" },
        new() { Value = "ay-BO", DisplayName = "Aymara (*Bolivia)" },
        new() { Value = "az", DisplayName = "Azerbaijani" },
        new() { Value = "az-AZ", DisplayName = "Azerbaijani (*Azerbaijan)" },
        new() { Value = "az-Cyrl-AZ", DisplayName = "Azerbaijani (Azerbaijan, Cyrillic)" },
        new() { Value = "ba", DisplayName = "Bashkir" },
        new() { Value = "ba-RU", DisplayName = "Bashkir (*Russia)" },
        new() { Value = "eu", DisplayName = "Basque" },
        new() { Value = "eu-ES", DisplayName = "Basque (*Spain)" },
        new() { Value = "be", DisplayName = "Belarusian" },
        new() { Value = "be-BY", DisplayName = "Belarusian (*Belarus)" },
        new() { Value = "bn", DisplayName = "Bengali" },
        new() { Value = "bn-BD", DisplayName = "Bengali (*Bengladesh)" },
        new() { Value = "dz", DisplayName = "Bhutani" },
        new() { Value = "dz-BT", DisplayName = "Bhutani (*Bhutan)" },
        new() { Value = "bh", DisplayName = "Bihari" },
        new() { Value = "bh-IN", DisplayName = "Bihari (*India)" },
        new() { Value = "bi", DisplayName = "Bislama" },
        new() { Value = "bi-VU", DisplayName = "Bislama (*Vanuatu)" },
        new() { Value = "bs", DisplayName = "Bosnian" },
        new() { Value = "bs-BA", DisplayName = "Bosnian (*Bosnia and Herzegovina)" },
        new() { Value = "br", DisplayName = "Breton" },
        new() { Value = "br-FR", DisplayName = "Breton (*France)" },
        new() { Value = "bg", DisplayName = "Bulgarian" },
        new() { Value = "bg-BG", DisplayName = "Bulgarian (*Bulgaria)" },
        new() { Value = "my", DisplayName = "Burmese" },
        new() { Value = "my-MM", DisplayName = "Burmese (*Myanmar)" },
        new() { Value = "ca", DisplayName = "Catalan" },
        new() { Value = "ca-ES", DisplayName = "Catalan (*Spain)" },
        new() { Value = "zh", DisplayName = "Chinese" },
        new() { Value = "zh-CN", DisplayName = "Chinese (*China, =Simplified)" },
        new() { Value = "zh-HK", DisplayName = "Chinese (Hong-Kong)" },
        new() { Value = "zh-MO", DisplayName = "Chinese (Macau)" },
        new() { Value = "zh-SG", DisplayName = "Chinese (Singapore)" },
        new() { Value = "zh-TW", DisplayName = "Chinese (Taiwan, =Traditional)" },
        new() { Value = "zh-Hans", DisplayName = "Chinese (Simplified)" },
        new() { Value = "zh-Hant", DisplayName = "Chinese (Traditional)" },
        new() { Value = "kw", DisplayName = "Cornish Gaelic" },
        new() { Value = "kw-GB", DisplayName = "Cornish Gaelic (*United Kingdom)" },
        new() { Value = "co", DisplayName = "Corsican" },
        new() { Value = "co-FR", DisplayName = "Corsican (*France)" },
        new() { Value = "ht", DisplayName = "Haitian Creole" },
        new() { Value = "ht-HT", DisplayName = "Haitian Creole (*Haiti)" },
        new() { Value = "hr", DisplayName = "Croatian" },
        new() { Value = "hr-HR", DisplayName = "Croatian (*Croatia)" },
        new() { Value = "hr-BA", DisplayName = "Croatian (Bosnia and Herzegovina)" },
        new() { Value = "cs", DisplayName = "Czech" },
        new() { Value = "cs-CZ", DisplayName = "Czech (*Czech Republic)" },
        new() { Value = "da", DisplayName = "Danish" },
        new() { Value = "da-DK", DisplayName = "Danish (Denmark)" },
        new() { Value = "snm", DisplayName = "Dhivehi" },
        new() { Value = "snm-MV", DisplayName = "Dhivehi (*Maldives)" },
        new() { Value = "nl", DisplayName = "Dutch" },
        new() { Value = "nl-NL", DisplayName = "Dutch (*The Netherlands)" },
        new() { Value = "nl-BE", DisplayName = "Dutch (Belgium, =Flemish)" },
        new() { Value = "nl-SR", DisplayName = "Dutch (Surinam)" },
        new() { Value = "en", DisplayName = "English" },
        new() { Value = "en-US", DisplayName = "English (*United States)" },
        new() { Value = "en-AU", DisplayName = "English (Australia)" },
        new() { Value = "en-BS", DisplayName = "English (Bahamas)" },
        new() { Value = "en-BB", DisplayName = "English (Barbados)" },
        new() { Value = "en-BZ", DisplayName = "English (Belize)" },
        new() { Value = "en-CA", DisplayName = "English (Canada)" },
        new() { Value = "en-DM", DisplayName = "English (Dominica)" },
        new() { Value = "en-GM", DisplayName = "English (Gambia)" },
        new() { Value = "en-GH", DisplayName = "English (Ghana)" },
        new() { Value = "en-GD", DisplayName = "English (Grenada)" },
        new() { Value = "en-GY", DisplayName = "English (Guyana)" },
        new() { Value = "en-IE", DisplayName = "English (Ireland)" },
        new() { Value = "en-IN", DisplayName = "English (India)" },
        new() { Value = "en-JM", DisplayName = "English (Jamaica)" },
        new() { Value = "en-KI", DisplayName = "English (Kiribati)" },
        new() { Value = "en-LS", DisplayName = "English (Lesotho)" },
        new() { Value = "en-LR", DisplayName = "English (Liberia)" },
        new() { Value = "en-MW", DisplayName = "English (Malawi)" },
        new() { Value = "en-MU", DisplayName = "English (Mauritius)" },
        new() { Value = "en-NA", DisplayName = "English (Namibia)" },
        new() { Value = "en-NZ", DisplayName = "English (New Zealand)" },
        new() { Value = "en-NG", DisplayName = "English (Nigeria)" },
        new() { Value = "en-PG", DisplayName = "English (Papua New-Guinea)" },
        new() { Value = "en-PH", DisplayName = "English (Philippines)" },
        new() { Value = "en-ZA", DisplayName = "English (South Africa)" },
        new() { Value = "en-SL", DisplayName = "English (Sierra Leone)" },
        new() { Value = "en-VC", DisplayName = "English (St Vincent and the Grenadines)" },
        new() { Value = "en-TT", DisplayName = "English (Trinidad and Tobago)" },
        new() { Value = "en-GB", DisplayName = "English (United Kingdom)" },
        new() { Value = "x-en-Carib", DisplayName = "English (Windows Caribbean)" },
        new() { Value = "x-en-Neutral", DisplayName = "English (Windows Neutral)" },
        new() { Value = "en-ZM", DisplayName = "English (Zambia)" },
        new() { Value = "en-ZW", DisplayName = "English (Zimbabwe)" },
        new() { Value = "eo", DisplayName = "Esperanto" },
        new() { Value = "et", DisplayName = "Estonian" },
        new() { Value = "et-EE", DisplayName = "Estonian (*Estonia)" },
        new() { Value = "fo", DisplayName = "Faeroese" },
        new() { Value = "fo-FO", DisplayName = "Faeroese (*Faeroese Islands)" },
        new() { Value = "fa", DisplayName = "Farsi" },
        new() { Value = "fa-IR", DisplayName = "Farsi (*Iran)" },
        new() { Value = "fj", DisplayName = "Fijian" },
        new() { Value = "fj-FJ", DisplayName = "Fijian (*Fiji)" },
        new() { Value = "fi", DisplayName = "Finnish" },
        new() { Value = "fi-FI", DisplayName = "Finnish (*Finland)" },
        new() { Value = "fr", DisplayName = "French" },
        new() { Value = "fr-FR", DisplayName = "French (*France)" },
        new() { Value = "fr-BE", DisplayName = "French (Belgium)" },
        new() { Value = "fr-BF", DisplayName = "French (Burkina Faso)" },
        new() { Value = "fr-CM", DisplayName = "French (Cameroon)" },
        new() { Value = "fr-CA", DisplayName = "French (Canada, =Québécois)" },
        new() { Value = "fr-TD", DisplayName = "French (Chad)" },
        new() { Value = "fr-KM", DisplayName = "French (Comoros)" },
        new() { Value = "fr-CG", DisplayName = "French (Congo)" },
        new() { Value = "fr-CI", DisplayName = "French (Côte d'Ivoire)" },
        new() { Value = "fr-DJ", DisplayName = "French (Djibouti)" },
        new() { Value = "fr-GA", DisplayName = "French (Gabon)" },
        new() { Value = "fr-GN", DisplayName = "French (Guinea)" },
        new() { Value = "fr-HT", DisplayName = "French (Haiti)" },
        new() { Value = "fr-LU", DisplayName = "French (Luxembourg)" },
        new() { Value = "fr-ML", DisplayName = "French (Mali)" },
        new() { Value = "fr-MR", DisplayName = "French (Mauritania)" },
        new() { Value = "fr-MC", DisplayName = "French (Monaco)" },
        new() { Value = "fr-SN", DisplayName = "French (Senegal)" },
        new() { Value = "fr-CH", DisplayName = "French (Switzerland)" },
        new() { Value = "fr-TG", DisplayName = "French (Togo)" },
        new() { Value = "fr-ZR", DisplayName = "French (Zaire)" },
        new() { Value = "fy", DisplayName = "Frisian" },
        new() { Value = "fy-NL", DisplayName = "Frisian (*The Netherlands)" },
        new() { Value = "gl", DisplayName = "Galician" },
        new() { Value = "gl-ES", DisplayName = "Gallegan (*Spain)" },
        new() { Value = "ka", DisplayName = "Georgian" },
        new() { Value = "ka-GE", DisplayName = "Georian (*Georgia)" },
        new() { Value = "de", DisplayName = "German" },
        new() { Value = "de-DE", DisplayName = "German (*Germany)" },
        new() { Value = "de-AT", DisplayName = "German (Austria)" },
        new() { Value = "de-LI", DisplayName = "German (Liechtenstein)" },
        new() { Value = "de-LU", DisplayName = "German (Luxembourg)" },
        new() { Value = "de-CH", DisplayName = "German (Switzerland)" },
        new() { Value = "gil", DisplayName = "Gilbertese" },
        new() { Value = "gil-KI", DisplayName = "Gilbertese (*Kiribati)" },
        new() { Value = "gil-TV", DisplayName = "Gilbertese (Tuvalu)" },
        new() { Value = "el", DisplayName = "Greek" },
        new() { Value = "el-GR", DisplayName = "Greek (*Greece)" },
        new() { Value = "el-CY", DisplayName = "Greek (Cyprus)" },
        new() { Value = "gn", DisplayName = "Guarani" },
        new() { Value = "gn-PY", DisplayName = "Guarani (*Paraguay)" },
        new() { Value = "gu", DisplayName = "Gujarati" },
        new() { Value = "gu-IN", DisplayName = "Gujarati (*India)" },
        new() { Value = "ha", DisplayName = "Hausa" },
        new() { Value = "ha-NG", DisplayName = "Hausa (*Nigeria)" },
        new() { Value = "he", DisplayName = "Hebrew" },
        new() { Value = "he-IL", DisplayName = "Hebrew (*Israel)" },
        new() { Value = "hi", DisplayName = "Hindi" },
        new() { Value = "hi-IN", DisplayName = "Hindi (*India)" },
        new() { Value = "hu", DisplayName = "Hungarian" },
        new() { Value = "hu-HU", DisplayName = "Hungarian (*Hungarian)" },
        new() { Value = "is", DisplayName = "Icelandic" },
        new() { Value = "is-IS", DisplayName = "Icelandic (*Iceland)" },
        new() { Value = "id", DisplayName = "Indonesian" },
        new() { Value = "id-id", DisplayName = "Indonesian (*Indonesia)" },
        new() { Value = "ia", DisplayName = "Interlingua" },
        new() { Value = "ie", DisplayName = "Interlingue" },
        new() { Value = "iu", DisplayName = "Inuktitut" },
        new() { Value = "iu-CA", DisplayName = "Inuktitut (*Canada)" },
        new() { Value = "ik", DisplayName = "Inupiak" },
        new() { Value = "ik-US", DisplayName = "Inupiak (*United States)" },
        new() { Value = "ga", DisplayName = "Irish Gaelic" },
        new() { Value = "ga-IE", DisplayName = "Irish Gaelic (*Ireland)" },
        new() { Value = "it", DisplayName = "Italian" },
        new() { Value = "it-IT", DisplayName = "Italian (*Italy)" },
        new() { Value = "it-SM", DisplayName = "Italian (San Marino)" },
        new() { Value = "it-CH", DisplayName = "Italian (Switzerland)" },
        new() { Value = "ja", DisplayName = "Japanese" },
        new() { Value = "ja-JP", DisplayName = "Japanese (*Japan)" },
        new() { Value = "jw", DisplayName = "Javanese" },
        new() { Value = "jw-ID", DisplayName = "Javanese (*Indonesia)" },
        new() { Value = "kl", DisplayName = "Kalaallisut" },
        new() { Value = "kl-GL", DisplayName = "Kalaallisut (*Greenland)" },
        new() { Value = "kn", DisplayName = "Kannada" },
        new() { Value = "kn-IN", DisplayName = "Kannada (*India)" },
        new() { Value = "ks", DisplayName = "Kashmiri" },
        new() { Value = "ks-IN", DisplayName = "Kashmiri (*India)" },
        new() { Value = "kk", DisplayName = "Kazakh" },
        new() { Value = "kk-KZ", DisplayName = "Kazakh (*Kazakhstan)" },
        new() { Value = "rw", DisplayName = "Kinyarwanda" },
        new() { Value = "rw-RW", DisplayName = "Kinyarwanda (*Rwanda)" },
        new() { Value = "ky", DisplayName = "Kirghiz" },
        new() { Value = "ky-KG", DisplayName = "Kirghiz (*Kyrgyzstan)" },
        new() { Value = "rn", DisplayName = "Kirundi" },
        new() { Value = "rn-BI", DisplayName = "Kirundi (*Burundi)" },
        new() { Value = "km", DisplayName = "Khmer" },
        new() { Value = "km-KH", DisplayName = "Khmer (*Cambodia)" },
        new() { Value = "kok", DisplayName = "Konkani" },
        new() { Value = "kok-IN", DisplayName = "Konkani (*India)" },
        new() { Value = "ko", DisplayName = "Korean" },
        new() { Value = "ko-KR", DisplayName = "Korean (*Korea)" },
        new() { Value = "ko-KP", DisplayName = "Korean (North Korea)" },
        new() { Value = "lo", DisplayName = "Lao" },
        new() { Value = "lo-LA", DisplayName = "Lao (*Laos)" },
        new() { Value = "lap", DisplayName = "Lappish" },
        new() { Value = "lap-NO", DisplayName = "Lappish (*Norway)" },
        new() { Value = "la", DisplayName = "Latin" },
        new() { Value = "la-VA", DisplayName = "Latin (*Vatican)" },
        new() { Value = "lv", DisplayName = "Latvian" },
        new() { Value = "lv-LV", DisplayName = "Latvian (*Latvia)" },
        new() { Value = "ln", DisplayName = "Lingala" },
        new() { Value = "ln-CG", DisplayName = "Lingala (*Congo)" },
        new() { Value = "lt", DisplayName = "Lithuanian" },
        new() { Value = "lt-LT", DisplayName = "Lithuanian (*Lithuania)" },
        new() { Value = "x-lt-LT-Classic", DisplayName = "Lithuanian (Lithuania, Classical)" },
        new() { Value = "lb", DisplayName = "Luxemburgian" },
        new() { Value = "lb-LU", DisplayName = "Luxemburgian (*Luxembourg)" },
        new() { Value = "mk", DisplayName = "Macedonian" },
        new() { Value = "mk-MK", DisplayName = "Macedonian (*Macedonia)" },
        new() { Value = "mg", DisplayName = "Malagasy" },
        new() { Value = "mg-MG", DisplayName = "Malagasy (*Madagascar)" },
        new() { Value = "ms", DisplayName = "Malay" },
        new() { Value = "ms-MY", DisplayName = "Malay (*Malaysia)" },
        new() { Value = "ms-BN", DisplayName = "Malay (Brunei Darussalam)" },
        new() { Value = "ml", DisplayName = "Malayalam" },
        new() { Value = "ml-IN", DisplayName = "Malayalam (*India)" },
        new() { Value = "mt", DisplayName = "Maltese" },
        new() { Value = "mt-MT", DisplayName = "Maltese (*Malta)" },
        new() { Value = "mni", DisplayName = "Manipuri" },
        new() { Value = "mni-IN", DisplayName = "Manipuri (*India)" },
        new() { Value = "gv", DisplayName = "Manx Gaelic" },
        new() { Value = "gv-GB", DisplayName = "Manx Gaelic (*United Kingdom)" },
        new() { Value = "mi", DisplayName = "Maori" },
        new() { Value = "mi-NZ", DisplayName = "Maori (*New Zealand)" },
        new() { Value = "mr", DisplayName = "Marathi" },
        new() { Value = "mr-IN", DisplayName = "Marathi (*India)" },
        new() { Value = "mo", DisplayName = "Moldovan" },
        new() { Value = "mo-MD", DisplayName = "Moldovan (*Moldova)" },
        new() { Value = "mn", DisplayName = "Mongolian" },
        new() { Value = "mn-MN", DisplayName = "Mongolian (*Mongolia)" },
        new() { Value = "na", DisplayName = "Nauruan" },
        new() { Value = "na-NR", DisplayName = "Nauruan (*Nauru)" },
        new() { Value = "nv", DisplayName = "Navajo" },
        new() { Value = "nv-US", DisplayName = "Navajo (*United States)" },
        new() { Value = "ne", DisplayName = "Nepali" },
        new() { Value = "ne-NP", DisplayName = "Nepali (*Nepal)" },
        new() { Value = "ne-IN", DisplayName = "Nepali (India)" },
        new() { Value = "no", DisplayName = "Norwegian" },
        new() { Value = "no-NO", DisplayName = "Norwegian (*Norway)" },
        new() { Value = "nn-NO", DisplayName = "Norwegian Nynorsk (*Norway)" },
        new() { Value = "oc", DisplayName = "Occitan" },
        new() { Value = "oc-FR", DisplayName = "Occitan (*France)" },
        new() { Value = "or", DisplayName = "Oriya" },
        new() { Value = "or-IN", DisplayName = "Oriya (*India)" },
        new() { Value = "ps", DisplayName = "Pashto" },
        new() { Value = "ps-AF", DisplayName = "Pashto (*Afghanistan)" },
        new() { Value = "pl", DisplayName = "Polish" },
        new() { Value = "pl-PL", DisplayName = "Polish (*Poland)" },
        new() { Value = "pt", DisplayName = "Portuguese" },
        new() { Value = "pt-BR", DisplayName = "Portuguese (*Brazil)" },
        new() { Value = "pt-AO", DisplayName = "Portuguese (Angola)" },
        new() { Value = "pt-CV", DisplayName = "Portuguese (Cape Verde)" },
        new() { Value = "pt-GW", DisplayName = "Portuguese (Guinea-Bissau)" },
        new() { Value = "pt-MZ", DisplayName = "Portuguese (Mozambique)" },
        new() { Value = "pt-PT", DisplayName = "Portuguese (Portugal)" },
        new() { Value = "pa", DisplayName = "Punjabi" },
        new() { Value = "pa-IN", DisplayName = "Punjabi (*India)" },
        new() { Value = "qu", DisplayName = "Quechua" },
        new() { Value = "qu-PE", DisplayName = "Quechua (*Peru)" },
        new() { Value = "ro", DisplayName = "Romanian" },
        new() { Value = "ro-ro", DisplayName = "Romanian (*Romania)" },
        new() { Value = "ro-md", DisplayName = "Romanian (Moldova)" },
        new() { Value = "rm", DisplayName = "Raetho-Roman" },
        new() { Value = "rm-ch", DisplayName = "Raetho-Roman (*Switzerland)" },
        new() { Value = "ru", DisplayName = "Russian" },
        new() { Value = "ru-ru", DisplayName = "Russian (*Russia)" },
        new() { Value = "ru-md", DisplayName = "Russian (Moldova)" },
        new() { Value = "sa", DisplayName = "Sanskrit" },
        new() { Value = "sa-in", DisplayName = "Sanskrit (*India)" },
        new() { Value = "sd", DisplayName = "Sindhi" },
        new() { Value = "sd-in", DisplayName = "Sindhi (*India)" },
        new() { Value = "si", DisplayName = "Singhalese" },
        new() { Value = "si-lk", DisplayName = "Singhalese (*Sri-Lanka)" },
        new() { Value = "sk", DisplayName = "Slovak" },
        new() { Value = "sk-sk", DisplayName = "Slovak (*Slovakia)" },
        new() { Value = "sl", DisplayName = "Slovenian" },
        new() { Value = "sl-si", DisplayName = "Slovenian (*Slovenia)" },
        new() { Value = "sm", DisplayName = "Samoan" },
        new() { Value = "sm-ws", DisplayName = "Samoan (*Western Samoa)" },
        new() { Value = "sq", DisplayName = "Albanian" },
        new() { Value = "sq-AL", DisplayName = "Albanian (*Albania)" },
        new() { Value = "sr", DisplayName = "Serbian" },
        new() { Value = "sr-Cyrl-SP", DisplayName = "Serbian (*Serbia)" },
        new() { Value = "sr-Cyrl-BA", DisplayName = "Serbian (Bosnia and Herzegovina)" },
        new() { Value = "ss", DisplayName = "Siswati" },
        new() { Value = "ss-sz", DisplayName = "Siswati (*Swaziland)" },
        new() { Value = "ss-za", DisplayName = "Siswati (South-Africa)" },
        new() { Value = "st", DisplayName = "Sesotho" },
        new() { Value = "st-ls", DisplayName = "Sesotho (*Lesotho)" },
        new() { Value = "sv", DisplayName = "Swedish" },
        new() { Value = "sv-SE", DisplayName = "Swedish (*Sweden)" },
        new() { Value = "sv-AX", DisplayName = "Swedish (Åland Islands)" },
        new() { Value = "sv-FI", DisplayName = "Swedish (Finland)" },
        new() { Value = "sw", DisplayName = "Swahili" },
        new() { Value = "sw-KE", DisplayName = "Swahili (*Kenya)" },
        new() { Value = "syr", DisplayName = "Syriac" },
        new() { Value = "gd", DisplayName = "Scottish Gaelic" },
        new() { Value = "gd-GB", DisplayName = "Scottish Gaelic (*United Kingdom)" },
        new() { Value = "tet", DisplayName = "Tetum" },
        new() { Value = "tet-TL", DisplayName = "Tetum (*Timor-Leste)" },
        new() { Value = "yo", DisplayName = "Yoruba" },
        new() { Value = "yo-NG", DisplayName = "Yoruba (*Nigeria)" },
        new() { Value = "yi", DisplayName = "Yiddish" },
        new() { Value = "yi-IL", DisplayName = "Yiddish (*Israel)" },
        new() { Value = "vi", DisplayName = "Vietnamese" },
        new() { Value = "vi-VN", DisplayName = "Vietnamese (*Vietnam)" },
        new() { Value = "wo", DisplayName = "Wolof" },
        new() { Value = "wo-SN", DisplayName = "Wolof (*Senegal)" },
        new() { Value = "wen", DisplayName = "Sorbian" },
        new() { Value = "wen-DE", DisplayName = "Sorbian (*Germany)" },
        new() { Value = "x-win-Neutral", DisplayName = "Windows Neutral" },
        new() { Value = "x-win-Default", DisplayName = "Windows Neutral (Default)" },
        new() { Value = "x-win-System", DisplayName = "Windows Neutral (System)" },
        new() { Value = "bo", DisplayName = "Tibetan" },
        new() { Value = "bo-ZH", DisplayName = "Tibetan (*China)" },
        new() { Value = "cy", DisplayName = "Welsh" },
        new() { Value = "cy-GB", DisplayName = "Welsh (*United Kingdom)" },
        new() { Value = "es", DisplayName = "Spanish" },
        new() { Value = "es-ES", DisplayName = "Spanish (*Spain)" },
        new() { Value = "es-AR", DisplayName = "Spanish (Argentina)" },
        new() { Value = "es-BO", DisplayName = "Spanish (Bolivia)" },
        new() { Value = "es-CL", DisplayName = "Spanish (Chile)" },
        new() { Value = "es-CO", DisplayName = "Spanish (Colombia)" },
        new() { Value = "es-CR", DisplayName = "Spanish (Costa Rica)" },
        new() { Value = "es-CU", DisplayName = "Spanish (Cuba)" },
        new() { Value = "es-DO", DisplayName = "Spanish (Dominican Republic)" },
        new() { Value = "es-EC", DisplayName = "Spanish (Ecuador)" },
        new() { Value = "es-GQ", DisplayName = "Spanish (Equatorial Guinea)" },
        new() { Value = "es-GT", DisplayName = "Spanish (Guatemala)" },
        new() { Value = "es-HN", DisplayName = "Spanish (Honduras)" },
        new() { Value = "es-MX", DisplayName = "Spanish (Mexico)" },
        new() { Value = "es-NI", DisplayName = "Spanish (Nicaragua)" },
        new() { Value = "es-PA", DisplayName = "Spanish (Panama)" },
        new() { Value = "es-PE", DisplayName = "Spanish (Peru)" },
        new() { Value = "es-PR", DisplayName = "Spanish (Puerto Rico)" },
        new() { Value = "es-PY", DisplayName = "Spanish (Paraguay)" },
        new() { Value = "es-SV", DisplayName = "Spanish (El Salvador)" },
        new() { Value = "es-UY", DisplayName = "Spanish (Uruguay)" },
        new() { Value = "es-VE", DisplayName = "Spanish (Venezuela)" },
        new() { Value = "es-419", DisplayName = "Spanish (Latin American &amp; the Caribbean)" },
        new() { Value = "es-x-Modern", DisplayName = "Spanish (Modern Sort)" },
        new() { Value = "th", DisplayName = "Thai" },
        new() { Value = "th-TH", DisplayName = "Thai (*Thailand)" },
        new() { Value = "tr", DisplayName = "Turkish" },
        new() { Value = "tr-TR", DisplayName = "Turkish (*Turkey)" },
        new() { Value = "tr-CY", DisplayName = "Turkish (Cyprus)" },
        new() { Value = "uk", DisplayName = "Ukrainian" },
        new() { Value = "uk-UA", DisplayName = "Ukrainian (*Ukraine)" },
        new() { Value = "ur", DisplayName = "Urdu" },
        new() { Value = "uk-PK", DisplayName = "Urdu (*Pakistan)" },
        new() { Value = "ug", DisplayName = "Uighur" },
        new() { Value = "ug-CN", DisplayName = "Uighur (*China)" },
        new() { Value = "zu", DisplayName = "Zulu" },
        new() { Value = "zu-ZA", DisplayName = "Zulu (*south Africa)" },
    ];
}